name = "web-site"
type = "javascript"

[vars]
NODE_VERSION = "20.9.0"
NPM_VERSION = "9.6.7"

[build]
command = "npm install --no-optional && npm run build"

[env.production]
pages_build_output_dir = "./dist"
